version: '3.8' 

volumes:
  postgres-db:

services:
  api:
    image: bgbatsy/fastapi:v1
    ports:
      - "80:9000"
    env_file:
      - ./.env
    # command: uvicorn app.main:app --host 0.0.0.0 --port 9000


  postgres:
    image: postgres

    environment:
      - POSTGRES_PASSWORD=$(psp)
      - POSTGRES_DB=$(psdb)

    env_file:
      - ./.env
    ports:
      - "5432:5432" 
    volumes:
      - postgres-db:/var/lib/postgresql