version: '3.8' 

volumes:
  postgres-db:

services:
  api:
    image: fastapi:latest
    volumes:
      - ./:/usr/src/app:ro
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload


  postgres:
    image: postgres

    environment:
      - POSTGRES_PASSWORD=2005
      - POSTGRES_DB=fastapi

    env_file:
      - ./.env
    ports:
      - "5432:5432" 
    volumes:
      - postgres-db:/var/lib/postgresql

 
    
     