name:  Build and Deploy code

on: [push, pull_request]

jobs:
 job1:
    env:
      DB_pass: 2005
      DB_user: postgres
      DB_host: localhost
      DB: fastapi
      key: 6d113339c4073c706d0f4d4214d028160d2c69e88c8898f4382e7ccf9c11a719
      algo: HS256
      DATABASE_URL: postgresql://postgres:2005@localhost:5432/fastapi
      psp: 2005
      psdb: fastapi
    runs-on: ubuntu-latest
    steps:
      - name: pulls git repo
        uses: actions/checkout@v2
      - name: install python version 3.14.4
        uses: actions/setup-python@v2
        with:
          python-version: "3.14.4"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest